M48
; DRILL file {KiCad 6.0.11+dfsg-1~bpo11+1} date Sa 21 Okt 2023 13:11:06 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-21T13:11:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1~bpo11+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.500
%
G90
G05
T1
X52.92Y93.215
X58.7Y93.215
T2
X74.86Y6.0
T3
X5.0Y95.036
X5.0Y5.036
X95.0Y95.0
X95.0Y5.0
T0
M30
